from django.contrib import admin
from .models import *

admin.site.register(User)
admin.site.register(communication)
admin.site.register(Article)
admin.site.register(BlogPost)
admin.site.register(Magazine)
admin.site.register(Category)
admin.site.register(HotNews)
admin.site.register(HotNewsImage)
admin.site.register(TrendingNews)
admin.site.register(TrendingNewsImage)
admin.site.register(BreakingNewsImage)
admin.site.register(BreakingNews)
admin.site.register(LastNews)
admin.site.register(LastNewsImage)
admin.site.register(Subscriber)
admin.site.register(GalleryImages)
admin.site.register(UpcomingEvents)
admin.site.register(EventRegistration)
admin.site.register(Comment)
admin.site.register(Members)
admin.site.register(ArchiveNews)
admin.site.register(StateNews)
admin.site.register(NationalNews)
admin.site.register(SportsNews)
admin.site.register(AgricultureTrending)
admin.site.register(ArchiveNewsComment)
# admin.site.register()


