# Generated by Django 5.1 on 2024-09-17 13:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakingNewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/panchayat_sandesh_logo.png', upload_to='images/breaking-news/')),
                ('image_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(default='images/panchayat_sandesh_logo.png', upload_to='images/category_images')),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/gallery_images')),
                ('name', models.CharField(default='gallery_image', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HotNewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/panchayat_sandesh_logo.png', upload_to='images/hot-news/')),
                ('image_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LastNewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/panchayat_sandesh_logo.png', upload_to='images/last-news/')),
                ('image_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('magazine_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('magazine_title', models.CharField(default='none', max_length=100)),
                ('issue_number', models.IntegerField()),
                ('description', models.TextField()),
                ('publication_date', models.DateField()),
                ('cover_image', models.ImageField(upload_to='images/magazine/')),
                ('pdf_file', models.FilePathField(path='media/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingNewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/panchayat_sandesh_logo.png', upload_to='images/trending-news/')),
                ('image_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('no_of_registers', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BreakingNews',
            fields=[
                ('news_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(default='Anurag Tiwari', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.breakingnewsimage')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('blogpost_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(default='Anurag Tiwari', max_length=100)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('featured_image', models.ImageField(upload_to='media/images')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Archive', 'Archive'), ('Not Published', 'Not Published')], max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default=100)),
                ('author', models.CharField(default='Anurag Tiwari', max_length=100)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('featured_image', models.ImageField(upload_to='media/images')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Archive', 'Archive'), ('Not Published', 'Not Published')], max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='HotNews',
            fields=[
                ('news_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(default='Anurag Tiwari', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.hotnewsimage')),
            ],
        ),
        migrations.CreateModel(
            name='LastNews',
            fields=[
                ('news_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(default='Anurag Tiwari', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.lastnewsimage')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingNews',
            fields=[
                ('news_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(default='Anurag Tiwari', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.trendingnewsimage')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='news_app.upcomingevents')),
            ],
        ),
    ]
