# Generated by Django 5.1.6 on 2025-02-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
