# Generated by Django 5.1.6 on 2025-03-30 20:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgricultureTrending',
            fields=[
                ('news_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('news_type', models.CharField(choices=[('Krishi News', 'Krishi News'), ('Horticulture News', 'Horticulture News'), ('Animal Husbandry News', 'Animal Husbandry News')], max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('images', models.ImageField(upload_to='images/agriculture-trending/')),
                ('author', models.CharField(default='Anurag Tiwari', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NationalNews',
            fields=[
                ('news_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('images', models.ImageField(upload_to='images/national-news/')),
                ('author', models.CharField(default='Anurag Tiwari', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportsNews',
            fields=[
                ('news_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('images', models.ImageField(upload_to='images/sports-news/')),
                ('author', models.CharField(default='Anurag Tiwari', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateNews',
            fields=[
                ('news_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('images', models.ImageField(upload_to='images/state-news/')),
                ('author', models.CharField(default='Anurag Tiwari', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
