# Generated by Django 5.1.6 on 2025-03-31 21:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_agriculturetrending_nationalnews_sportsnews_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveNews',
            fields=[
                ('news_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('news_type', models.CharField(choices=[('Krishi News', 'Krishi News'), ('Horticulture News', 'Horticulture News'), ('Animal Husbandry News', 'Animal Husbandry News')], max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('images', models.ImageField(upload_to='images/agriculture-trending/')),
                ('author', models.CharField(default='Government of India', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
