# Generated by Django 5.1.6 on 2025-03-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_alter_archivenews_news_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivenews',
            name='comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archivenews',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
