# Generated by Django 5.1.6 on 2025-03-31 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0010_archivenews_comments_archivenews_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivenews',
            name='images',
            field=models.ImageField(upload_to='images/archive-news/'),
        ),
        migrations.CreateModel(
            name='ArchiveNewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anonymous', max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to='news_app.archivenews')),
            ],
        ),
    ]
